-- 0048_visit_attribution.sql — "who was on this visit" at the visit level.
-- Reuses the project-wide convention: solo_profile IS NULL = "both of us",
-- solo_profile = X = that person only (same as activities & places).
--
-- Visits are regenerated by rebuild_place_visits(), so attribution is INFERRED
-- from the day's activities on each rebuild (a joint activity ⇒ Both; only one
-- person's runs ⇒ that person; mixed/none ⇒ Both). A manual chip in the UI sets
-- solo_override=true, which the rebuild carries forward (like it does notes) so a
-- hand-correction survives future regenerations.
--
-- Photo uploader is deliberately NOT used as a signal: auto-ingest is Erica-only,
-- so it would mislabel every photo-only day as "just me".

alter table public.visits
  add column if not exists solo_profile  uuid references public.profiles(id),   -- null = both of us
  add column if not exists solo_override boolean not null default false;         -- true = human-set, keep across rebuilds

create or replace function public.rebuild_place_visits(p_place uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if p_place is null then return; end if;

  create temp table _isl on commit drop as
  with days as (
    select coalesce(taken_at, created_at)::date d from public.photos
      where place_id = p_place and coalesce(taken_at, created_at) is not null
    union select start_date::date from public.activities
      where place_id = p_place and start_date is not null
    union select recorded_at::date from public.location_pings where place_id = p_place
    union select date::date from public.entries
      where place_id = p_place and date is not null
  ),
  dd  as (select distinct d from days),
  grp as (select d, d - (row_number() over (order by d))::int as isl from dd)
  select min(d) as s, max(d) as e from grp group by isl;

  -- For each new island: snapshot notes, carry any manual attribution override
  -- from an overlapping old visit, and infer attribution from the day's activities.
  create temp table _isln on commit drop as
  select i.s, i.e,
    (select string_agg(v.note, ' / ' order by v.start_date) from public.visits v
       where v.place_id = p_place and v.note is not null
         and v.start_date <= i.e and v.end_date >= i.s) as note,
    exists (select 1 from public.visits v
       where v.place_id = p_place and v.solo_override
         and v.start_date <= i.e and v.end_date >= i.s) as ovr,
    (select v.solo_profile from public.visits v
       where v.place_id = p_place and v.solo_override
         and v.start_date <= i.e and v.end_date >= i.s
       order by v.start_date limit 1) as ovr_profile,
    (with a as (
        select count(*) as n,
               bool_or(solo_profile is null) as has_joint,
               array_agg(distinct solo_profile) filter (where solo_profile is not null) as solos
        from public.activities
          where place_id = p_place and start_date::date between i.s and i.e)
     select case
       when n = 0 then null                               -- no activities → Both (override later if wanted)
       when has_joint then null                           -- a joint activity → Both
       when array_length(solos, 1) = 1 then solos[1]      -- exactly one person
       else null end                                      -- mixed solos → Both
     from a) as inferred
  from _isl i;

  delete from public.visits where place_id = p_place;
  insert into public.visits (place_id, start_date, end_date, note, solo_profile, solo_override)
    select p_place, s, e, note,
           case when ovr then ovr_profile else inferred end,
           ovr
    from _isln;

  drop table if exists _isl;
  drop table if exists _isln;
end $$;

-- Backfill: recompute every place so visits pick up inferred attribution.
do $$
declare pid uuid;
begin
  for pid in
    select id from public.places p where exists (
      select 1 from public.visits v where v.place_id = p.id
      union all select 1 from public.activities a where a.place_id = p.id
      union all select 1 from public.photos ph where ph.place_id = p.id
      union all select 1 from public.entries e where e.place_id = p.id
      union all select 1 from public.location_pings lp where lp.place_id = p.id
    )
  loop
    perform public.rebuild_place_visits(pid);
  end loop;
end $$;
